// <auto-generated />
using System;
using DirectWholesaleSupply.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable
#pragma warning disable 612, 618

namespace DirectWholesaleSupply.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("DirectWholesaleSupply.Models.AuditLog", b =>
            {
                b.Property<int>("LogID").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Details").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("LogDate").HasColumnType("datetime2");
                b.Property<int>("UserID").HasColumnType("int");
                b.HasKey("LogID");
                b.HasIndex("UserID");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.Category", b =>
            {
                b.Property<int>("CategoryID").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("CategoryName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("SortOrder").HasColumnType("int");
                b.HasKey("CategoryID");
                b.ToTable("Categories");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.PriceHistory", b =>
            {
                b.Property<int>("HistoryID").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<DateTime>("ChangedAt").HasColumnType("datetime2");
                b.Property<decimal>("NewRetailPrice").HasColumnType("decimal(10,2)");
                b.Property<decimal>("NewWholesalePrice").HasColumnType("decimal(10,2)");
                b.Property<decimal>("OldRetailPrice").HasColumnType("decimal(10,2)");
                b.Property<decimal>("OldWholesalePrice").HasColumnType("decimal(10,2)");
                b.Property<int>("ProductID").HasColumnType("int");
                b.Property<int>("UserID").HasColumnType("int");
                b.HasKey("HistoryID");
                b.HasIndex("ProductID");
                b.HasIndex("UserID");
                b.ToTable("PriceHistories");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.Product", b =>
            {
                b.Property<int>("ProductID").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<int>("CategoryID").HasColumnType("int");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Notes").HasMaxLength(255).HasColumnType("nvarchar(255)");
                b.Property<string>("ProductName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<decimal>("RetailPrice").HasColumnType("decimal(10,2)");
                b.Property<int>("SortOrder").HasColumnType("int");
                b.Property<string>("Unit").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<decimal>("WholesalePrice").HasColumnType("decimal(10,2)");
                b.HasKey("ProductID");
                b.HasIndex("CategoryID");
                b.ToTable("Products");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.Role", b =>
            {
                b.Property<int>("RoleID").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("RoleName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("RoleID");
                b.ToTable("Roles");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.User", b =>
            {
                b.Property<int>("UserID").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Password").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("RoleID").HasColumnType("int");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.HasKey("UserID");
                b.HasIndex("RoleID");
                b.ToTable("Users");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.AuditLog", b =>
            {
                b.HasOne("DirectWholesaleSupply.Models.User", "User")
                    .WithMany("AuditLogs").HasForeignKey("UserID")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.PriceHistory", b =>
            {
                b.HasOne("DirectWholesaleSupply.Models.Product", "Product")
                    .WithMany("PriceHistories").HasForeignKey("ProductID")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("DirectWholesaleSupply.Models.User", "User")
                    .WithMany("PriceHistories").HasForeignKey("UserID")
                    .OnDelete(DeleteBehavior.NoAction).IsRequired();
                b.Navigation("Product");
                b.Navigation("User");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.Product", b =>
            {
                b.HasOne("DirectWholesaleSupply.Models.Category", "Category")
                    .WithMany("Products").HasForeignKey("CategoryID")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Category");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.User", b =>
            {
                b.HasOne("DirectWholesaleSupply.Models.Role", "Role")
                    .WithMany("Users").HasForeignKey("RoleID")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Role");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.Category", b =>
            { b.Navigation("Products"); });

            modelBuilder.Entity("DirectWholesaleSupply.Models.Role", b =>
            { b.Navigation("Users"); });

            modelBuilder.Entity("DirectWholesaleSupply.Models.User", b =>
            {
                b.Navigation("AuditLogs");
                b.Navigation("PriceHistories");
            });

            modelBuilder.Entity("DirectWholesaleSupply.Models.Product", b =>
            { b.Navigation("PriceHistories"); });
        }
    }
}
